/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import javax.swing.text.DefaultCaret;
import java.awt.Frame;
import java.util.Objects;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Abdul
 */
public class Music_interface extends javax.swing.JFrame {

    JFileChooser filechooser;
    FileNameExtensionFilter filter = new FileNameExtensionFilter("MP3 Files", "mp3");
    private final MusicPlayer musicPlayer;
    /**
     * Creates new form Music_interface
     */
    public Music_interface() {
        initComponents();
        musicPlayer=new MusicPlayer(this);
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        Close = new javax.swing.JLabel();
        Minimize = new javax.swing.JLabel();
        LeftPanel = new javax.swing.JPanel();
        BrowseLabel = new javax.swing.JLabel();
        BottomPanel = new javax.swing.JPanel();
        ImagePanel = new javax.swing.JPanel();
        ImageLabel = new javax.swing.JLabel();
        NamePanel = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        Previous = new javax.swing.JLabel();
        PausePlay = new javax.swing.JLabel();
        Next = new javax.swing.JLabel();
        Slider = new javax.swing.JSlider();
        songTimeLabel = new javax.swing.JLabel();
        songTotalTimeLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        MainPanel.setBackground(new java.awt.Color(0, 32, 63));

        TopPanel.setBackground(new java.awt.Color(173, 239, 209));

        Close.setFont(new java.awt.Font("Geist", 1, 24)); // NOI18N
        Close.setForeground(new java.awt.Color(0, 0, 0));
        Close.setText("X");
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        Minimize.setFont(new java.awt.Font("Geist", 1, 24)); // NOI18N
        Minimize.setForeground(new java.awt.Color(0, 0, 0));
        Minimize.setText("_");
        Minimize.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
                TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Minimize)
                                .addGap(37, 37, 37)
                                .addComponent(Close)
                                .addContainerGap())
        );
        TopPanelLayout.setVerticalGroup(
                TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(TopPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Close, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(53, Short.MAX_VALUE))
        );

        LeftPanel.setBackground(new java.awt.Color(173, 239, 209));

        BrowseLabel.setFont(new java.awt.Font("Geist", 0, 24)); // NOI18N
        BrowseLabel.setForeground(new java.awt.Color(0, 0, 0));
        BrowseLabel.setText("Browse..");
        BrowseLabel.setToolTipText("");
        BrowseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BrowseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BrowseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BrowseLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
                LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LeftPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BrowseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addContainerGap())
        );
        LeftPanelLayout.setVerticalGroup(
                LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LeftPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(BrowseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BottomPanel.setBackground(new java.awt.Color(173, 239, 209));
        BottomPanel.setForeground(new java.awt.Color(156, 156, 210));

        ImagePanel.setBackground(new java.awt.Color(173, 239, 209));

        ImageLabel.setBackground(new java.awt.Color(173, 239, 209));
        ImageLabel.setFont(new java.awt.Font("Geist Dark",0,24));
        ImageLabel.setForeground(new java.awt.Color(0, 0, 0));
        ImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout ImagePanelLayout = new javax.swing.GroupLayout(ImagePanel);
        ImagePanel.setLayout(ImagePanelLayout);
        ImagePanelLayout.setHorizontalGroup(
                ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ImagePanelLayout.createSequentialGroup()
                                .addComponent(ImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        ImagePanelLayout.setVerticalGroup(
                ImagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ImagePanelLayout.createSequentialGroup()
                                .addComponent(ImageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                .addContainerGap())
        );

        NamePanel.setBackground(new java.awt.Color(173, 239, 209));

        NameLabel.setBackground(new java.awt.Color(173, 239, 209));
        NameLabel.setFont(new java.awt.Font("Geist", 1, 18)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(0, 0, 0));
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout NamePanelLayout = new javax.swing.GroupLayout(NamePanel);
        NamePanel.setLayout(NamePanelLayout);
        NamePanelLayout.setHorizontalGroup(
                NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(NamePanelLayout.createSequentialGroup()
                                .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                .addContainerGap())
        );
        NamePanelLayout.setVerticalGroup(
                NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        Previous.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/back.png")))); // NOI18N

        PausePlay.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/play.png")))); // NOI18N
        PausePlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PausePlayMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PausePlayMouseEntered(evt);
            }
        });

        Next.setBackground(new java.awt.Color(102, 102, 102));
        Next.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/next.png")))); // NOI18N

        Slider.setMinorTickSpacing(10);
        Slider.setSnapToTicks(true);
        Slider.addChangeListener(this::SliderStateChanged);
        Slider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SliderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SliderMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                SliderMouseReleased(evt);
            }
        });

        songTimeLabel.setForeground(new java.awt.Color(0, 0, 0));
        songTimeLabel.setText("0:00");

        songTotalTimeLabel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout BottomPanelLayout = new javax.swing.GroupLayout(BottomPanel);
        BottomPanel.setLayout(BottomPanelLayout);
        BottomPanelLayout.setHorizontalGroup(
                BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BottomPanelLayout.createSequentialGroup()
                                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ImagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(songTimeLabel)
                                .addGap(18, 18, 18)
                                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(BottomPanelLayout.createSequentialGroup()
                                                .addComponent(Previous)
                                                .addGap(79, 79, 79)
                                                .addComponent(PausePlay)
                                                .addGap(79, 79, 79)
                                                .addComponent(Next))
                                        .addComponent(Slider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(songTotalTimeLabel)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        BottomPanelLayout.setVerticalGroup(
                BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BottomPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ImagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomPanelLayout.createSequentialGroup()
                                                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(songTimeLabel)
                                                        .addComponent(songTotalTimeLabel))
                                                .addGap(18, 18, 18)
                                                .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(PausePlay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(BottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(Previous, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(18, 18, 18)
                                .addComponent(NamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jTextArea1.setBackground(new java.awt.Color(0, 32, 63));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Geist", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Sorry, no lyrics available :(");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setCaretColor(new java.awt.Color(0, 0, 0));
        jTextArea1.setSelectionColor(new java.awt.Color(255, 255, 255));
        DefaultCaret caret = (DefaultCaret)jTextArea1.getCaret();
        caret.setUpdatePolicy(DefaultCaret.NEVER_UPDATE); // Prevent auto-scrolling
        caret.setDot(0);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                        .addComponent(TopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
                MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(TopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void PausePlayMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        if(musicPlayer.isPlaying){
            musicPlayer.pauseSong();
            musicPlayer.isPlaying=false;
            PausePlay.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/play.png"))));
        }
        else{
            musicPlayer.playSong();
            musicPlayer.isPlaying=true;
            PausePlay.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/pause.png"))));
        }

    }

    private void PausePlayMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void SliderMousePressed(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        musicPlayer.isPlaying=false;
        musicPlayer.pauseSong();
        musicPlayer.timeWhenSongPaused=0;
        PausePlay.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/play.png"))));
    }

    private void SliderMouseReleased(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        javax.swing.JSlider source=(javax.swing.JSlider) evt.getSource();
        musicPlayer.currentFrame=source.getValue();
        musicPlayer.seek =(int)(musicPlayer.currentFrame/(musicPlayer.getSongNowPlaying().getFramerate()));
        musicPlayer.playSong();
        PausePlay.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/pause.png"))));
    }

    private void SliderMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void BrowseLabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        filechooser=new JFileChooser();
        filechooser.setFileFilter(filter);
        int result=filechooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            // Get the selected file
            if(musicPlayer.isPlaying){
                musicPlayer.pauseSong();}
            musicPlayer.songpath= filechooser.getSelectedFile().getPath();
            musicPlayer.NewSongSelected=true;
            musicPlayer.playSong();
            musicPlayer.pausePosition=0;
            PausePlay.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/pause.png"))));
        }
        if (musicPlayer.getSongNowPlaying() != null) {
            jTextArea1.setText(musicPlayer.getSongNowPlaying().getLyrics());
            NameLabel.setText(musicPlayer.getSongNowPlaying().getname());
            ImageLabel.setIcon(musicPlayer.getSongNowPlaying().getIcon());
            songTotalTimeLabel.setText(MusicPlayer.formatTime(musicPlayer.getSongNowPlaying().getLengthinSeconds()));
            Slider.setMaximum(musicPlayer.getSongNowPlaying().getmp3file().getFrameCount());
        } else {
            jTextArea1.setText("Sorry, no lyrics available :(");
            ImageLabel.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/play.png"))));
        }
    }

    private void BrowseLabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        BrowseLabel.setFont(new java.awt.Font("Geist", 1, 24));
    }

    private void BrowseLabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        BrowseLabel.setFont(new java.awt.Font("Geist", 0, 24));
    }

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    private void MinimizeMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        Music_interface.super.setExtendedState(Frame.ICONIFIED);
    }

    private void SliderStateChanged(javax.swing.event.ChangeEvent evt) {
        // TODO add your handling code here:

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException |
                 UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Music_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Music_interface().setVisible(true));
    }


    // Variables declaration - do not modify
    private javax.swing.JPanel BottomPanel;
    private javax.swing.JLabel BrowseLabel;
    private javax.swing.JLabel Close;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel Minimize;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JLabel Next;
    private javax.swing.JLabel PausePlay;
    private javax.swing.JLabel Previous;
    public javax.swing.JSlider Slider;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel songTimeLabel;
    private javax.swing.JLabel songTotalTimeLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration

    public void setSongTimeLabel(String value) {
        songTimeLabel.setText(value);
    }

    public void setPausePlayIcon(Icon icon){
        PausePlay.setIcon(icon);
    }

}
